apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-06-08T05:19:47Z"
  labels:
    version: v1
    zone: prod
  name: nginx
  namespace: default
  resourceVersion: "16048"
  uid: 9a660ed2-c68e-4f99-982d-93e7cf8b4e87
spec:
  containers:
  - image: apasoft/nginx:v1
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-r2v8d
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cluster-desa-m02
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-r2v8d
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-06-08T05:19:47Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-06-08T05:19:57Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-06-08T05:19:57Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-06-08T05:19:47Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://bf4dbc84f01115188bc364030bc8c2e6d370798c3742e30382a1d1604ce227a4
    image: apasoft/nginx:v1
    imageID: docker-pullable://apasoft/nginx@sha256:45b3154692ef8073f8b22dd70012fedf6e25c9a1dda7aa83b27ac28332a15e64
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-06-08T05:19:56Z"
  hostIP: 192.168.58.3
  phase: Running
  podIP: 10.244.1.4
  podIPs:
  - ip: 10.244.1.4
  qosClass: BestEffort
  startTime: "2024-06-08T05:19:47Z"
